### ISSUE TITLE
Pod restarted after PipelineRun deleted.

### ISSUE THREAD

**Issue by hyunuck** [tektoncd/dashboard#1226]
# Expected behavior
Show status of PipelineRun

# Actual behavior
Pod restarted

# Steps to reproduce the problem

1. kubectl -n <namespace> delete -f <pipeline_run>

# Environment
- Kubernetes Platform: kubernetes cloud working on openstack.

- Tekton Pipelines version:
v0.11.0-rc4

- Tekton Dashboard version:
v0.6.0

# Additional Info
```
{"level":"debug","msg":"Secret Controller detected secret 'git-ssh' deleted"}
{"level":"debug","msg":"Secret Controller detected secret 'robot-git-ssh-token-gpqlt' deleted"}
{"level":"debug","msg":"PipelineResource Controller detected pipelineResource 'pipeline-git-repo' deleted"}
{"level":"debug","msg":"Task Controller detected task 'list-pipeline-repo-files' deleted"}
{"level":"debug","msg":"Task Controller detected task 'build-pipeline-repo-files' deleted"}
{"level":"debug","msg":"Pipeline Controller detected pipeline 'pipeline-list-pipeline-repo-files' deleted"}
{"level":"debug","msg":"PipelineRun Controller detected pipelineRun 'demo-condtional-pr-without-condition-resource' deleted"}
E0402 09:15:51.231931       1 runtime.go:78] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x13c50c0), concrete:(*runtime._type)(0x145f300), asserted:(*runtime._type)(0x1587460), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.ServiceAccount)
goroutine 178 [running]:
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1400080, 0xc0000b3620)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1400080, 0xc0000b3620)
	runtime/panic.go:679 +0x1b2
github.com/tektoncd/dashboard/pkg/controllers/kubernetes.serviceAccountDeleted(0x145f300, 0xc0007485e0)
	github.com/tektoncd/dashboard/pkg/controllers/kubernetes/serviceAccount.go:61 +0x157
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/controller.go:212
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1, 0x0, 0x0)
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/shared_informer.go:660 +0x1d6
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00053ddd8, 0x0, 0xc0003a4eb8)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00018f740)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00053df40, 0xdf8475800, 0x0, 0x42cf01, 0xc0005650e0)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000532180)
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00051c1b0, 0xc000534f40)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.ServiceAccount [recovered]
	panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.ServiceAccount

goroutine 178 [running]:
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1400080, 0xc0000b3620)
	runtime/panic.go:679 +0x1b2
github.com/tektoncd/dashboard/pkg/controllers/kubernetes.serviceAccountDeleted(0x145f300, 0xc0007485e0)
	github.com/tektoncd/dashboard/pkg/controllers/kubernetes/serviceAccount.go:61 +0x157
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/controller.go:212
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x1, 0x0, 0x0)
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/shared_informer.go:660 +0x1d6
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc0007f7dd8, 0x0, 0xc0003a4eb8)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:292 +0x51
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/shared_informer.go:652 +0x79
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00018f740)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0007f7f40, 0xdf8475800, 0x0, 0x42cf01, 0xc0005650e0)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache.(*processorListener).run(0xc000532180)
	github.com/tektoncd/dashboard/vendor/k8s.io/client-go/tools/cache/shared_informer.go:650 +0x9b
github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00051c1b0, 0xc000534f40)
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x59
created by github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	github.com/tektoncd/dashboard/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by a-roberts** [comment]
Interesting file https://github.com/tektoncd/dashboard/blob/fec8e1d86e7bcc12f907face15b067aa62c68d55/pkg/controllers/kubernetes/serviceAccount.go

@hyunuck can you share the output of your `kubectl version`? I'm interested in the server version specifically. We've not seen this happen ever on OpenShift or Docker Desktop, apimachinery and the go-client versions are mentioned lots which I believe are linked to a minimum k8s version of 1.15, although I like to think you'd get a different error instead of this nasty one.

**Comment by a-roberts** [comment]
Also, can you provide your PipelineRun yaml please (if there's anything remotely sensitive just omit that), I'm looking for serviceaccount mentions (or serviceaccountname, or serviceaccountnames, that kinda thing) - wondering if it's specific to your type of PipelineRun and we need to update our backend code client versions to accomodate your spec.

**Comment by a-roberts** [comment]
Thanks @chhsia0 for the PR for this! 

Let's see if

/assign @chhsia0

works, you're not available from the assignee dropdown. I've been unable to reproduce this personally...
