### ISSUE TITLE
TaskRun API returning 502 when environment contains TaskRun with inline Task spec

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#149]
# Expected Behavior
Requests to `GET /v1/namespaces/<namespace>/taskrun/?name=<taskname>` should return the list of TaskRuns matching the specified Task name.

# Actual Behavior
Returns a 502 if a TaskRun with an inline Task spec (i.e. no standalone Task definition) exists in the namespace.

# Steps to Reproduce the Problem

1. Apply a Task + TaskRun (e.g. `kubectl apply -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/taskruns/task-env.yaml`)
1. Apply a TaskRun with an inline Task spec (e.g. `kubectl apply -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/taskruns/git-resource-spec-taskrun.yaml`)
1. In the dashboard, click the Tasks nav item and click on any task.
1. Observe the error, and 502 response in the network trace.

Removing the offending TaskRun restores functionality (e.g. `kubectl delete -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/taskruns/git-resource-spec-taskrun.yaml`)

# Additional Info
<details>
<summary>tekton-dashboard log</summary>

```
2019/05/15 20:07:32 http: panic serving 10.1.1.1:55600: runtime error: invalid memory address or nil pointer dereference
goroutine 3959 [running]:
net/http.(*conn).serve.func1(0xc0006fa000)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x116de00, 0x1f47ca0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/tektoncd/dashboard/pkg/endpoints.Resource.getAllTaskRuns(0x1475f60, 0xc00031ba30, 0x14bec80, 0xc00020cb00, 0xc0004dc1b0, 0xc000312000)
	/home/ibmadmin/go/src/github.com/tektoncd/dashboard/pkg/endpoints/pipeline.go:412 +0x321
github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0002b3e60, 0x147fbe0, 0xc00072c000, 0xc000194000)
	/home/ibmadmin/go/src/github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful/container.go:288 +0xa3b
net/http.HandlerFunc.ServeHTTP(0xc000343200, 0x147fbe0, 0xc00072c000, 0xc000194000)
	/usr/local/go/src/net/http/server.go:1995 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000320340, 0x147fbe0, 0xc00072c000, 0xc000194000)
	/usr/local/go/src/net/http/server.go:2375 +0x1d6
github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc0002b3e60, 0x147fbe0, 0xc00072c000, 0xc000194000)
	/home/ibmadmin/go/src/github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful/container.go:303 +0x4d
net/http.serverHandler.ServeHTTP(0xc00045c820, 0x147fbe0, 0xc00072c000, 0xc000194000)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0006fa000, 0x1487ce0, 0xc000486680)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```
</details>

**Comment by AlanGreene** [comment]
Verified the change fixes the issue 👍 Thanks
