### ISSUE TITLE
Reduce warnings in unit test output

### ISSUE THREAD

**Issue by AlanGreene** [tektoncd/dashboard#1793]
The logs for the frontend unit tests contain a lot of noise which can make it difficult to debug test failures.

Most of the warnings come from common components so they're repeated many times.

Including some of the most frequent examples for reference, but this is not an exhaustive list:

```
console.warn
  Unmatched GET to http://localhost/v1/token

  84 |
  85 | function getToken() {
> 86 |   return fetch(`${apiRoot}/v1/token`, {
     |          ^
  87 |     ...defaultOptions,
  88 |     headers: {
  89 |       Accept: 'text/plain'

  at Object.FetchMock.executeRouter (node_modules/fetch-mock/cjs/lib/fetch-handler.js:221:11)
  at Object.FetchMock._fetchHandler (node_modules/fetch-mock/cjs/lib/fetch-handler.js:144:34)
  at Object.fetch [as fetchHandler] (node_modules/fetch-mock/cjs/lib/fetch-handler.js:135:14)
  at getToken (src/api/comms.js:86:10)
  at request (src/api/comms.js:97:19)
  at post (src/api/comms.js:124:10)
  at createSecretAPI (src/api/secrets.js:34:10)
  at src/actions/secrets.js:158:13
```

```
console.warn
  Warning: You cannot change <Router history>

  at warning (node_modules/tiny-warning/dist/tiny-warning.cjs.js:13:15)
  at Router.componentDidUpdate (node_modules/react-router/modules/Router.js:81:5)
  at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:19835:22)
  at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:22803:7)
  at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:188:14)
  at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:330:27)
  at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:281:3)
  at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:228:9)
```

```
  Warning: Each child in a list should have a unique "key" prop.

  Check the render method of `LogFormat`. See https://fb.me/react-warning-keys for more information.
      in span (created by LogFormat)
      in LogFormat
      in IntlProvider

  270 |       );
  271 |     }
> 272 |     return <div key={index}>{line}</div>;
      |            ^
  273 |   };
  274 |
```

```
console.error
  Warning: Failed prop type: The prop `onChange` is marked as required in `ComboBox`, but its value is `undefined`.
      in ComboBox (created by TooltipDropdown)
      in TooltipDropdown (created by Context.Consumer)
      in injectIntl(TooltipDropdown) (created by PipelineResourcesDropdown)
      in PipelineResourcesDropdown (created by Context.Consumer)
      in injectIntl(PipelineResourcesDropdown) (created by ConnectFunction)
      in ConnectFunction
      in Provider
      in IntlProvider

  64 |     defaultMessage: 'No items found'
  65 |   });
> 66 |   return /*#__PURE__*/React.createElement(ComboBox, _extends({
     |                             ^
  67 |     className: className,
  68 |     disabled: disabled,
  69 |     id: id,
```

```
  Warning: Failed prop type: The prop `rows[0].id` is marked as required in `DataTable`, but its value is `undefined`.
      in DataTable (created by ResourceTable)
      in ResourceTable (created by StepDefinition)
      in StepDefinition (created by Context.Consumer)
      in injectIntl(StepDefinition)
      in IntlProvider
      in Router

  28 |   const { title, rows: rowParams, headers: headerParams } = props;
  29 |   return (
> 30 |     <DataTable
     |     ^
  31 |       rows={rowParams}
  32 |       headers={headerParams}
  33 |       size="short"

```

```
  Warning: Failed prop type: The prop `match.params.namespace` is marked as required in `SecretContainer`, but its value is `undefined`.
      in SecretContainer

  56 |
  57 |   const { getByText } = renderWithRouter(
> 58 |     <SecretContainer
     |     ^
  59 |       intl={intl}
  60 |       match={match}
  61 |       fetchSecret={() => Promise.resolve()}

```

Some of these may point at changes required in the components to relax the proptype checks (e.g. where we've marked something as `required` but it's actually optional and safe to omit), while most likely require a change in the tests to provide missing props / config.

By far the most frequent warning is the unmatched requests from fetch-mock. The tests should not be making real network requests, so we use `fetch-mock` to intercept these and return predefined responses. There are a number of tests that are not capturing all of the requests they're triggering so these will need to be updated to avoid making the requests in the first place or to ensure they're properly captured.

**Comment by AlanGreene** [comment]
PR opened to disable the fetch-mock warnings https://github.com/tektoncd/dashboard/pull/1838

After those, the noisiest remaining warnings relate to the `href` and `tabIndex` props of the Carbon Tab component. These props are deprecated, but we're not actually setting them anywhere in our code, so some investigation needed to determine if this is something that needs to be resolved by Carbon, or if there's something we can do to suppress them.

**Comment by AlanGreene** [comment]
PR #1838 produced a huge reduction in log output, ~4000 lines down to ~2000 for the same set of unit tests. This should make it much easier to spot and debug genuine issues.

I'll do another pass of the remaining warnings under our control to see if we can suppress them too before closing out this issue.

**Comment by AlanGreene** [comment]
PR open to remove most of the remaining warnings: https://github.com/tektoncd/dashboard/issues/1893

The only warnings left after that change are for a missing `key` prop in the LogFormat component in a few places mostly related to handling ANSI escape sequences and links. Resolving this warning is not trivial and could have negative consequences on the parsing. The warning is safe to ignore in this case so I propose closing the issue once #1893 is merged.

We may revisit this in future if it becomes overly noisy but for now it's a small number of logs in the output. We may even replace the LogFormat component entirely if we can find a suitable replacement that's performant enough (key features: fg/bg colours, text decoration, link formatting)
