### ISSUE TITLE
Ingress endpoint needs an error check (else panics)

### ISSUE THREAD

**Issue by a-roberts** [tektoncd/dashboard#373]
# Expected Behavior
We're getting a go panic if there's no ingress endpoint, so add a check to see if it's nil

# Actual Behavior
```
2019/07/24 10:02:09 http: panic serving 10.128.0.1:62661: runtime error: index out of range
goroutine 2676 [running]:
net/http.(*conn).serve.func1(0xc000404f00)
	/usr/local/go/src/net/http/server.go:1746 +0xd0
panic(0x1173340, 0x1ef3d30)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/tektoncd/dashboard/pkg/endpoints.Resource.GetIngress(0x1459ec0, 0xc000304c20, 0x1485920, 0xc000246800, 0xc0006699b0, 0xc000300770)
	/go/src/github.com/tektoncd/dashboard/pkg/endpoints/cluster.go:60 +0x211
github.com/tektoncd/dashboard/pkg/endpoints.Resource.GetIngress-fm(0xc0006699b0, 0xc000300770)
	/go/src/github.com/tektoncd/dashboard/pkg/router/router.go:111 +0x5f
github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc000127dd0, 0x1463fc0, 0xc0004d82a0, 0xc000684500)
	/go/src/github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful/container.go:285 +0xa18
github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful.(*Container).dispatch-fm(0x1463fc0, 0xc0004d82a0, 0xc000684500)
	/go/src/github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful/container.go:120 +0x48
net/http.HandlerFunc.ServeHTTP(0xc00035e160, 0x1463fc0, 0xc0004d82a0, 0xc000684500)
	/usr/local/go/src/net/http/server.go:1964 +0x44
net/http.(*ServeMux).ServeHTTP(0xc00031d650, 0x1463fc0, 0xc0004d82a0, 0xc000684500)
	/usr/local/go/src/net/http/server.go:2361 +0x127
github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful.(*Container).ServeHTTP(0xc000127dd0, 0x1463fc0, 0xc0004d82a0, 0xc000684500)
	/go/src/github.com/tektoncd/dashboard/vendor/github.com/emicklei/go-restful/container.go:300 +0x4d
net/http.serverHandler.ServeHTTP(0xc00032b930, 0x1463fc0, 0xc0004d82a0, 0xc000684500)
	/usr/local/go/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc000404f00, 0x1465100, 0xc00074ec40)
	/usr/local/go/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2851 +0x2f5
```

# Steps to Reproduce the Problem

1. Try to access v1/namespaces/tekton-pipelines/ingress without an ingress
2. Observe the crash

# Additional info
https://github.com/tektoncd/dashboard/blob/master/pkg/endpoints/cluster.go#L58 fix to go here

**Comment by a-roberts** [comment]
Now merged, closing
