### ISSUE TITLE
Dashboard breaks when trying to access pipeline/task runs

### ISSUE THREAD

**Issue by alan-ghelardi** [tektoncd/dashboard#693]
# Expected Behavior
The dashboard shows the pipeline/task run in question when I click over it. 
# Actual Behavior
When I run a pipeline via Triggers or creating it directly via the Dashboard and click over it or over one of its task runs, an empty page is displayed. By looking at the Javascript console, I saw the following error:
```shell
Error: "Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
        Ts http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:78414
        enqueueSetState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:46460
        setState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:69:1429
        _ http://192.168.99.100/main.fb83ad3156121feb3461.js:1:371339
        value http://192.168.99.100/main.fb83ad3156121feb3461.js:1:371723
        value http://192.168.99.100/main.fb83ad3156121feb3461.js:1:371556
        Us http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:94965
        unstable_runWithPriority http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:9:3878
        lo http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41497
        Us http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:90945
        As http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:79617
        ho http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41768
        unstable_runWithPriority http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:9:3878
        lo http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41497
        ho http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41714
        po http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41649
        Ts http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:78608
        enqueueSetState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:46460
        setState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:69:1429
        _ http://192.168.99.100/main.fb83ad3156121feb3461.js:1:215369
        l http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:46:538854
        _invoke http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:46:538644
        t http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:46:539273
        n http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:83:34505
        s http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:83:34715
        Q http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:23:49431
        r http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:54:11685
vendors.aca89a18cebd6eaf84b9.js:91:71744
Unhandled promise rejection Error: "Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
        Ts http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:78414
        enqueueSetState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:46460
        setState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:69:1429
        _ http://192.168.99.100/main.fb83ad3156121feb3461.js:1:371339
        value http://192.168.99.100/main.fb83ad3156121feb3461.js:1:371723
        value http://192.168.99.100/main.fb83ad3156121feb3461.js:1:371556
        Us http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:94965
        unstable_runWithPriority http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:9:3878
        lo http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41497
        Us http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:90945
        As http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:79617
        ho http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41768
        unstable_runWithPriority http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:9:3878
        lo http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41497
        ho http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41714
        po http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:41649
        Ts http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:78608
        enqueueSetState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:91:46460
        setState http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:69:1429
        _ http://192.168.99.100/main.fb83ad3156121feb3461.js:1:215369
        l http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:46:538854
        _invoke http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:46:538644
        t http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:46:539273
        n http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:83:34505
        s http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:83:34715
        Q http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:23:49431
        r http://192.168.99.100/vendors.aca89a18cebd6eaf84b9.js:54:11685
vendors.aca89a18cebd6eaf84b9.js:35:17314
``` 
The Dashboard's logs show the following entries:
```shell
{"level":"debug","msg":"PipelineRun Controller detected pipelineRun 'clj-lib-run-88kxl' updated"}
{"level":"debug","msg":"In getAllExtensions"}
{"level":"debug","msg":"Extensions: []"}
{"level":"debug","msg":"Upgrading connection to websocket..."}
{"level":"error","msg":"Error: the server could not find the requested resource"}
{"level":"error","msg":"websocket connection to client lost: websocket: close 1000 (normal)"}
```

# Steps to Reproduce the Problem

1. Install the manifest files attached (those reproduce the exact setup that I'm using to run Tekton locally).
2. Run the request.sh file that simulates a Github Webhook request calling the Event Listener endpoint or create a new pipeline run via the dashboard.  
3. Click over the clj-lib-run displayed in the Pipeline runs tab or over one of the task runs available.

# Additional Info

The attached files reproduce my local setup, including ingresses and persistent volumes to run the pipelines. The image nubank/clojure:lein-2.9.1 is a simple Debian based image with the latest version of Leiningen installed. I'm running Tekton on Minikube with the latest available versions of Pipelines, Trigger and Dashboard.
[tekton-files.tar.gz](https://github.com/tektoncd/dashboard/files/3805911/tekton-files.tar.gz)

**Comment by a-roberts** [comment]
Reproduced this OK with the following as small as possible set up:

```
Adams-MBP:tekton-files aroberts$ k apply -f pipelines/
pipeline.tekton.dev/clj-lib created

Adams-MBP:tekton-files aroberts$ k apply -f tasks/
task.tekton.dev/clj-lib-build created
task.tekton.dev/clj-lib-release created
task.tekton.dev/clj-lib-unit-test created

Adams-MBP:tekton-files aroberts$ k apply -f resources/
pipelineresource.tekton.dev/dummy-clj-lib created
```

Using Tekton 0.7 (0.8 isn't yet supported), clicking the Pipeline and Task info itself is fine (so yet to do a run).

- Created a manual PipelineRun
- Namespace tekton-pipelines (my install namespace for the Tekton Dashboard too)
- Pipeline is clj-lib
- Resource is dummy-clj-lib
- Service account is tekton-dashboard
- Timeout set to 60 min (default)

We indeed fail to render anything and here's the console output in dev mode:

```
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23115:28)
    at checkForNestedUpdates (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23118:7)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21389:3)
    at Object.enqueueSetState (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:13100:5)
    at Task.Component.setState (webpack-internal:///./node_modules/react/cjs/react.development.js:325:16)
    at Task.eval [as handleStepSelected] (webpack-internal:///./packages/components/dist/components/Task/Task.js:83:13)
    at Task.selectDefaultStep (webpack-internal:///./packages/components/dist/components/Task/Task.js:114:14)
    at Task.selectDefaultStep (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js:708:25)
    at Task.componentDidUpdate (webpack-internal:///./packages/components/dist/components/Task/Task.js:100:12)
    at Task.componentDidUpdate (webpack-internal:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js:698:123)
react-dom.development.js?61bb:19814 The above error occurred in the <Task> component:
    in Task (created by TaskTree)
    in ol (created by TaskTree)
    in TaskTree (created by PipelineRunContainer)
    in div (created by PipelineRunContainer)
    in PipelineRunContainer (created by Context.Consumer)
    in injectIntl(PipelineRunContainer) (created by PipelineRunContainer)
    in PipelineRunContainer (created by Context.Consumer)
    in injectIntl(PipelineRunContainer) (created by ConnectFunction)
    in ConnectFunction (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in main (created by Content)
    in Content (created by App)
    in Router (created by HashRouter)
    in HashRouter (created by App)
    in IntlProvider (created by App)
    in App (created by ConnectFunction)
    in ConnectFunction (created by HotExportedConnect(App))
    in AppContainer (created by HotExportedConnect(App))
    in HotExportedConnect(App)
    in Provider
```

Will update once I've got a fix, the Pipeline itself looks sensible, so do the Tasks and the PipelineResource.

**Comment by a-roberts** [comment]
Fix is merged into master now so closing
