### ISSUE TITLE
Secret creation results in error notification

### ISSUE THREAD

**Issue by Megan-Wright** [tektoncd/dashboard#996]
# Expected behavior
 When I create a secret I should be able to see the secret added to the table and the success notification "Secret created successfully"

# Actual behavior
When I create a secret, I see this notification: 
![Screenshot 2020-02-04 at 10 51 44](https://user-images.githubusercontent.com/52741262/73738626-b21bd600-473c-11ea-94ab-6985c50e6bee.png)
However, on refreshing the page, the secret has still been created successfully.

# Steps to reproduce the problem

1. Navigate to the secrets panel
2. Create a secret 
3. Error appears

# Environment
- Kubernetes Platform:

OpenShift

- Tekton Pipelines version:

- Tekton Triggers version:

- Tekton Dashboard version:

# Additional Info

**Comment by a-roberts** [comment]
Yeah seeing this too

```

printWarning @ checkPropTypes.js?a15c:20
Secrets.js?510b:230 Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at eval (webpack-internal:///./src/containers/Secrets/Secrets.js:272:39)
    at Array.map (<anonymous>)
    at Secrets.render (webpack-internal:///./src/containers/Secrets/Secrets.js:252:38)
    at finishClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:17039:31)
    at updateClassComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:16994:24)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:18505:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:347:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:397:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:454:31)
    at beginWork$$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23217:7)
ErrorBoundary.js?9c7c:70 ErrorBoundary Object
```

**Comment by a-roberts** [comment]
We've got the secret created fine in-cluster but if we print the secret object in our map, sometimes it's without the username field (so secret.username) is defined. Working on this now with Megan

**Comment by a-roberts** [comment]
![image](https://user-images.githubusercontent.com/12814972/73741012-438d4700-4741-11ea-875b-b120334d0a71.png)

Also, loving the data breach error we get, making an issue for that now 😰

**Comment by a-roberts** [comment]
The `type` field occasionally doesn't appear as well.

**Comment by a-roberts** [comment]
https://github.com/tektoncd/dashboard/pull/1000 temp fix

**Comment by a-roberts** [comment]
Temporary fix is merged, @Megan-Wright's super PR is open that'll result in all data being known anyways which is the better approach, closing
